# Project information
site_name: Interview Note
site_description: 面试笔记（Interview Note）
site_author: HyperJ
site_url: https://hyperj.net/note.interview

# Repository
repo_name: hyperj/note.interview
repo_url: https://github.com/hyperj/note.interview
edit_uri: blob/master/docs

# Copyright
copyright: Copyright &copy; 2013 - <span id="cyear">2013</span> HyperJ <script type="text/javascript">document.getElementById("cyear").innerText=new Date().getFullYear();document.write(unescape("%3Cdiv id='cnzz_stat_icon_1275779234'%3E%3C/div%3E%3Cscript src='https://s5.cnzz.com/z_stat.php%3Fid%3D1275779234%26online%3D1%26show%3Dline' type='text/javascript'%3E%3C/script%3E"));</script>

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /assets/images/hyperj.ico
  logo: /assets/images/hyperj.png

# Customization
extra:
  social:
    - icon: fontawesome/solid/h-square
      link: https://hyperj.net
    - icon: fontawesome/brands/github
      link: https://github.com/hyperj
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hyperj

extra_css:
  - /assets/css/mkdocs/material.css

# Page tree
nav:
  - Home: index.md